# post http://localhost:3001/login
# Content-Type: application/json

# {
#     "username": "Becca",
#     "password": "123"
# }

post http://localhost:5000/sms
Content-Type: application/json

{
    "name": "Shivam",
    "username": "shivam1708",
    "phone": "8976339502"
}