# post http://localhost:3001/signup
# Content-Type: application/json

# {
#     "name": "Chirag",
#     "username": "chiru",
#     "password": "123",
#     "bank_accno": 5,
#     "usertype": "consumer"
# }
