# post http://localhost:3001/login
# Content-Type: application/json

# {
#     "username": "Becca",
#     "password": "123"
# }

post http://localhost:3000/getnear
Content-Type: application/json

{
    "lat": "19.0727",
    "lng": "72.8979",
    "dst": "30"
}